import random
from Creator import Creator
from Director import Director
from Juego import Juego

def main():
    juego = Juego()
    fm = Creator()
    juego.crearLaberinto2HabitacionesFM(fm)
    juego.crearLaberinto4H4BFM(fm)
    print(f"{juego.obtenerHabitacion(1)}")
    print(f"{juego.obtenerHabitacion(2)}")
    print(f"{juego.obtenerHabitacion(3)}")
    print(f"{juego.obtenerHabitacion(4)}")
    print(f"{juego.obtenerHabitacion(1).obtenerElementoOr(fm.fabricarNorte())}")
    print(f"{juego.obtenerHabitacion(1).obtenerElementoOr(fm.fabricarEste())}")
    print(f"{juego.obtenerHabitacion(1).obtenerElementoOr(fm.fabricarSur())}")
    print(f"{juego.obtenerHabitacion(1).obtenerElementoOr(fm.fabricarOeste())}")
    print(f"{juego.obtenerHabitacion(2).obtenerElementoOr(fm.fabricarNorte())}")
    print(f"{juego.obtenerHabitacion(2).obtenerElementoOr(fm.fabricarEste())}") 
    print(f"{juego.obtenerHabitacion(2).obtenerElementoOr(fm.fabricarSur())}")
    print(f"{juego.obtenerHabitacion(2).obtenerElementoOr(fm.fabricarOeste())}")
    print(f"{juego.obtenerHabitacion(3).obtenerElementoOr(fm.fabricarNorte())}")
    print(f"{juego.obtenerHabitacion(3).obtenerElementoOr(fm.fabricarEste())}")
    print(f"{juego.obtenerHabitacion(3).obtenerElementoOr(fm.fabricarSur())}")
    print(f"{juego.obtenerHabitacion(3).obtenerElementoOr(fm.fabricarOeste())}")
    print(f"{juego.obtenerHabitacion(4).obtenerElementoOr(fm.fabricarNorte())}")
    print(f"{juego.obtenerHabitacion(4).obtenerElementoOr(fm.fabricarEste())}")
    print(f"{juego.obtenerHabitacion(4).obtenerElementoOr(fm.fabricarSur())}")
    print(f"{juego.obtenerHabitacion(4).obtenerElementoOr(fm.fabricarOeste())}")
    print(f"{juego.bichos[0]} {juego.bichos[0].posicion}")
    print(f"{juego.bichos[1]} {juego.bichos[1].posicion}")
    print(f"{juego.bichos[2]} {juego.bichos[2].posicion}")
    print(f"{juego.bichos[3]} {juego.bichos[3].posicion}")

    hab1 = juego.obtenerHabitacion(1)
    print(f"{hab1.obtenerElementoOr(fm.fabricarSur())}")
    juego.abrirPuertas()
    juego.cerrarPuertas()
    juego.abrirPuertas()
    ba1 = juego.bichos[0]
    print(f"{ba1.posicion}")
    hab2 = juego.obtenerHabitacion(2)
    hab2.entrar(ba1)
    print(f"{ba1.estaVivo()}")
    ba1.vidas = 10
    juego.agregarPersonaje("Surmania")
    ba1.actua()
    juego.lanzarBichos()
    #juego.terminarBicho(ba1)
    #juego.terminarBichos()
    person = juego.person
    person.irAlEste()
    person.irAlOeste()
    person.irAlNorte()
    person.irAlSur()
    person.atacar()
    person.atacar()
    person.atacar()
    person.atacar()
    person.atacar()
    person.atacar()
    person.atacar()
    person.atacar()
    person.atacar()
    person.atacar()
    person.atacar()
    person.atacar()
    person.atacar()
    person.atacar()
    person.atacar()
    person.atacar()
    person.atacar()
    person.atacar()
    person.atacar()
    person.atacar()
    person.atacar()
    person.atacar()
    person.atacar()
    person.atacar()
    director = Director()
    #director.procesar(r'C:\Users\alexr\Desktop\UCLM\Ano_3\Cuatrimestre 2\Diseño software\laberintos\lab2HTunel.json')
    #juego= director.obtenerJuego()
    juego.lanzarBichos()
    juego.terminarBichos()
    person.irAlEste()
    person.irAlOeste()
    person.irAlNorte()
    person.irAlSur()
    juego.abrirPuertas()
    juego.cerrarPuertas()


if __name__ == "__main__":
    main()