Class {
	#name : #Visitor,
	#superclass : #Object,
	#category : #'JuegoLaberinto-Visitor'
}

{ #category : #'as yet unclassified' }
Visitor >> visitarArmario:unArmario [

	


]

{ #category : #'as yet unclassified' }
Visitor >> visitarBomba:unaBomba [

	


]

{ #category : #'as yet unclassified' }
Visitor >> visitarHabitacion:unHab [
	


]

{ #category : #'as yet unclassified' }
Visitor >> visitarPared:unPared [
]

{ #category : #'as yet unclassified' }
Visitor >> visitarPuerta:unPuerta [
	


]

{ #category : #'as yet unclassified' }
Visitor >> visitarTunel:unTunel [
	


]
